forward internal errors instead of timeout status codes
convertersystems/opc-ua-client pull request #263
Opened 2023-12-01 09:54 UTC by trivalik

Fixes https://github.com/convertersystems/opc-ua-client/issues/236

The only question for me is should we leave the _exception list filled with the exception or can we consume it.

2023-12-10 18:51 UTC, awcullen requested changes

2023-12-10 18:51 UTC, awcullen commented on UaClient/ServiceModel/Ua/Channels/CommunicationObject.cs
As you commented, this won't be needed if we use GetPendingException.

2023-12-10 18:51 UTC, awcullen commented on UaClient/ServiceModel/Ua/Channels/ClientSecureChannel.cs
We should consume the exception.  May I suggest:
```
using (var timeoutCts = new CancellationTokenSource((int)request.RequestHeader!.TimeoutHint))
using (var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(timeoutCts.Token, _channelCts.Token, token))
using (var registration = linkedCts.Token.Register(o => ((ServiceOperation)o!).TrySetException(GetPendingException() ?? new ServiceResultException(StatusCodes.BadRequestTimeout)), operation, false))
{
```

2023-12-10 23:27 UTC, merged

2023-12-13 09:11 UTC, trivalik commented
@awcullen you missed to remove `PeakFirstPendingException()`

Is there a release planed?

2024-01-02 08:41 UTC, trivalik commented
@awcullen is there a planned to push a release to nuget.org?